- copy:
    src: hosts
    dest: /etc/hosts

- selinux:
    state: disabled

- shell: dnf -y copr enable seeitcoming/rcm && dnf -y install rcm
  when: ansible_distribution == 'Fedora'

- dnf: name={{ item }} state=latest
  with_items:
    - python3
    - python3-pip
    - python
    - python-pip
    - golang
    - ghc
    - cabal-install

    - zsh
    - tmux
    - screen
    - vim
    - emacs

    - git
    - subversion
    - mercurial

    - lynx
    - links

    - rubygem-rake
    - bmake
    - shake
    - ninja-build

    - docker
    - ansible
    - gawk
    - nmap
    - bind-utils
    - tig
    - htop
    - sl
